Chore/117 reduce shiki bundle size
poporonnet/kaniwriter pull request #138
Opened 2024-07-06 16:14 UTC by kiharu3112

close #117 
本当にこれでいいのかわかってない
<img width="440" alt="image" src="https://github.com/poporonnet/kaniwriter/assets/74781355/ec6a4d04-2048-41f0-8d5c-951433d335d8">

2024-07-08 06:08 UTC, tufusa requested changes
[must]
`sourceCode`が変わるたびに`highlighter`が再生成されているので、1回だけ生成されるようにしてください。別の`useEffect`にするか、カスタムフックにするのが一番良いと思います。

[imo]
今の状態は`shiki/wasm`と`shiki/themes/github-light.mjs`と`shiki/themes/github-light.mjs`がすべて`index.js`に展開されているので、ある程度チャンク分割をしたほうが良い可能性があります。
`vite.config.ts`の`build.rollupOptions.output.manualChunks`でチャンクを制御できたはずです。

2024-07-08 06:09 UTC, tufusa commented on src/components/SourceCodeTab.tsx
> +  // ソースコードをシンタックスハイライト付きのHMTLにする
typo `HMTL`

2024-07-14 12:08 UTC, tufusa commented on src/components/SourceCodeTab.tsx
>    }, [sourceCode]);
多分ロジックがおかしいです。
`createHighlighter`は非同期関数なので、`useEffect`に渡されているラムダは`createHighlighter`の完了を待ちません。仮に待ったとしても、`highlighter`が変更されるのは次回のレンダリングからです。したがって、その後の`convertCodeToHtml`の呼び出しは必ず失敗します (L31のEarly Returnに流れます) 。
今正しく動いているように見えるのは、`setHighlighter`が呼ばれるより`sourceCode`をフェッチしてくるほうが遅く、Dependency listに`sourceCode`があるから`setHighlighter`が呼ばれた後にこの`useEffect`が再トリガーされているためです。試しに、`setHighlighter`を呼ぶ前に
```ts
await new Promise((resolve) => setTimeout(resolve, 5000);
```
などとして5秒待ってみると動作しなくなるのが分かると思います。

2024-07-14 12:36 UTC, kiharu3112 commented
`highlighter`が変更された時に、もう一度`convertCodeToHtml`を実行するようにしたけど、これで大丈夫ですか。

2024-07-14 13:01 UTC, tufusa reviewed
👍　一件コメントしました、
ここまで来たらカスタムフックにしてしまうのはどうでしょうか？`useEffect`が複数あるのはあまり好ましくない気がします。

2024-07-14 13:01 UTC, tufusa commented on src/components/SourceCodeTab.tsx
> +        setHtml(html);
`codeToHtml`は非同期なので、非同期関数で包む必要はなさそうです。

2024-07-15 05:59 UTC, tufusa approved these changes
LGTM

2024-07-15 05:59 UTC, merged