feat:WebSerialAPIに対応していないブラウザで開くと警告のモーダルを出す
poporonnet/kaniwriter pull request #331
Opened 2024-12-01 14:32 UTC by kiharu3112

<img width="763" alt="image" src="https://github.com/user-attachments/assets/fcf481eb-6f36-4f13-8e89-d819389d86f1">
<img width="761" alt="image" src="https://github.com/user-attachments/assets/f285ad7f-4c59-441c-beb9-72aeb16505dc">

2024-12-02 03:06 UTC, kiharu3112 commented
なんで放置してたか思い出した
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/04d7bdb8-0e07-4054-ac2e-8ee426c1c476">

2024-12-02 03:44 UTC, tufusa requested changes
- ~~デフォルトでフォーカスが合った状態になるようで、ブラウザによっては枠線が表示されます。~~
- 幅が狭い環境でテキストと×アイコンが重なってしまうようです。
![image](https://github.com/user-attachments/assets/32910b7b-d361-4c4a-9e34-bed155cc482e)

2024-12-02 03:44 UTC, tufusa commented on i18n/locales/ja.json
> +  "対応するブラウザを使ってください": "お使いのブラウザではこのウェブサイトの一部機能が正しく動作しません。\nこのサイトのすべての機能を利用するためには、パソコンのGoogle ChromeやMicrosoft Edgeなどのブラウザを使用してください。"
この書き方だと"パソコンのブラウザ"なら良いように読めるので、
例えばFireFoxも含まれるように思えます。`デスクトップ版のGoogle ChromeもしくはMicrosoft Edge`のように明示したほうがよいでしょう。英語も同様です。

2024-12-02 03:44 UTC, tufusa commented on src/components/UnsupportedBrowserModal.tsx
> +  const [open, setOpen] = useState(true);
`useDisclosure`を使ってください。`GenerateMatchButton`などが参考になるでしょう。

2024-12-02 03:44 UTC, tufusa commented on src/pages/home.tsx
> +  const supported = "serial" in navigator;
```suggestion
  const isSupported = "serial" in navigator;
```

2024-12-02 03:44 UTC, tufusa commented on src/pages/home.tsx
> +      {!supported && <UnsupportedBrowserModal />}
こうするよりは、`defaultOpen`のようなプロパティを生やして`supported`を渡すのがよいでしょう。

2024-12-02 03:44 UTC, tufusa commented on src/components/UnsupportedBrowserModal.tsx
> +          alignItems={"center"}
```suggestion
          fontFamily="'M PLUS Rounded 1c', sans-serif"
          variant="h4"
          m={1}
          alignItems="center"
```
不要な括弧は削除してください。

2024-12-10 04:59 UTC, kiharu3112 commented on src/components/UnsupportedBrowserModal.tsx
> +  const [open, setOpen] = useState(true);
もしかしたらkcmsxと勘違いしてませんか

2024-12-10 05:11 UTC, tufusa commented on src/components/UnsupportedBrowserModal.tsx
> +  const [open, setOpen] = useState(true);
:kusa:

2024-12-10 05:28 UTC, tufusa requested changes

2024-12-10 05:28 UTC, tufusa commented on src/components/UnsupportedBrowserModal.tsx
> +  const supported = "serial" in navigator;
**サブコンポーネントに状態を持たないでください。**
例外は、ここでいう`open, setOpen`のようなUI制御のみに使われるそのコンポーネントでしか意味がない状態です(このモーダルが開いているかどうかは、親コンポーネントの何にも影響するとは思えません)。
`supported`は十分親コンポーネントで別の用途で使う可能性もあり、後から実装(=`"serial" in navigator`)を差し替えたい場合も考えられます。すなわち、サブコンポーネントに持つべき状態では**ありません。**

2024-12-10 05:39 UTC, kiharu3112 commented on src/components/UnsupportedBrowserModal.tsx
> +  const [open, setOpen] = useState(true);
:kusa:

2025-02-26 02:56 UTC, tufusa commented
> * デフォルトでフォーカスが合った状態になるようで、ブラウザによっては枠線が表示されます。

こちら私の間違いで、アクセシビリティ的に最初からフォーカスが合っているのが望ましいそうです。すみませんでした！
そこだけ戻すのをお願いします。

2025-03-12 06:36 UTC, tufusa approved these changes
LGTM

2025-03-12 06:36 UTC, merged